# Generated by Django 3.2.13 on 2022-04-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_alter_diary_expiration_alter_diary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.diary'),
        ),
    ]
